version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - 'curl -X POST --data-urlencode "payload={\"channel\": \"#times_sotanakamori\", \"username\": \"codebuild\", \"text\": \"@souta.nakamori Complete\", \"icon_emoji\": \":done:\"}" https://hooks.slack.com/services/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'
