version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
  build:
    commands:
      - which aws
      - aws --version
      - docker build -t development/codebuild-test .
      - docker tag development/codebuild-test:latest 111868999667.dkr.ecr.ap-northeast-1.amazonaws.com/development/codebuild-test:latest
  post_build:
    commands:
      - docker push 111868999667.dkr.ecr.ap-northeast-1.amazonaws.com/development/codebuild-test:latest
